---
stages:
- name: Build CLAMAV
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: stage
    enabled: false
  properties:
  - name: BLUE_GREEN
    type: text_area
    value: ${BLUE_GREEN}
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
      #!/bin/bash
       # get bluegreen script
      echo "$BLUE_GREEN" > bg.sh
- name: Deploy CLAMAV
  inputs:
  - type: job
    stage: Build CLAMAV
    job: Build
    dir_name: null
  properties:
  - name: ICON_DOMAIN
    type: text
    value: ${ICON_DOMAIN}
  - name: CLAMAV_MEM
    type: text
    value: ${CLAMAV_MEM}
  - name: CLAMAV_COUNT
    type: text
    value: ${CLAMAV_COUNT}
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      # deployment script
      deploy(){
        cf push ${CF_APP} -n ${CF_APP} -d ${ICON_DOMAIN} -f bluemix/base-manifest.yml --no-start
        cf scale -f -i ${CLAMAV_COUNT} -m ${CLAMAV_MEM} ${CF_APP} 
      }
      export -f deploy

      # get bluegreen script, which makes use of deploy
      chmod +x bg.sh
      ./bg.sh
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
