---
stages:
- name: Build ICONR2 UI
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: stage
    enabled: false
  properties:
  - name: BLUE_GREEN
    type: text_area
    value: ${BLUE_GREEN}
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
      #!/bin/bash
       # get bluegreen script
      echo "$BLUE_GREEN" > bg.sh
- name: Deploy ICONR2 UI
  inputs:
  - type: job
    stage: Build ICONR2 UI
    job: Build
    dir_name: null
  properties:
  - name: ICON_DOMAIN
    type: text
    value: ${ICON_DOMAIN}
  - name: ICON_SERVER_NAME
    type: text
    value: ${ICON_SERVER_NAME}
  - name: PHU_SELECT
    type: text
    value: ${PHU_SELECT}
  - name: FRONT_END_DOMAIN
    type: text
    value: ${FRONT_END_DOMAIN}
  - name: CUSTOM_PHU
    type: text
    value: ${CUSTOM_PHU}
  - name: FRONTEND_MEM
    type: text
    value: ${FRONTEND_MEM}
  - name: FRONTEND_COUNT
    type: text
    value: ${FRONTEND_COUNT}
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash    
      deploy(){
        cf push ${CF_APP}  -f bluemix/base-manifest.yml --no-start --no-route

        PHUs=
        if [ -z ${PHU_SELECT} ]
        then
          PHUs=${CUSTOM_PHU}
        else
          if [ ${PHU_SELECT} = "Full" ]
          then
            PHUs='xxsupportphu1,aph,bchu,ckphu,drhd,eohu,esthu,gbhu,hnhu,hkpr,hrhd,hph,hpechu,hchu,kfla,lph,lgl,mlhu,nrph,nbpsdhu,nwhu,oph,ocph,peel,pdhu,pcchu,po,rowph,re,smdhu,sdhu,tbdhu,timhu,tph,wdgph,wechu,yrphu' 
          else
            PHUs=${CUSTOM_PHU}
          fi
        fi

        for i in $(echo $PHUs | tr ',' ' ')
        do
          cf map-route ${CF_APP} ${FRONT_END_DOMAIN} --hostname $i
        done
      
        cf set-env ${CF_APP} ICON_SERVER https://${ICON_SERVER_NAME}.${ICON_DOMAIN}
      
        cf scale -f -i ${FRONTEND_COUNT} -m ${FRONTEND_MEM} ${CF_APP}
      }
      export -f deploy

      # run the deployment
      chmod +x bg.sh
      ./bg.sh
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
